### ISSUE TITLE
Investigate adding theme support for full-width blocks

### ISSUE THREAD

**Issue by Photosynthesis** [Foundation-For-Intentional-Community/Wordpress-Theme#37]

**Comment by resbraga** [comment]
Feature Branch:
https://github.com/Foundation-For-Intentional-Community/Wordpress-Theme/compare/feature/37-add-full-width-support

Currently, the home page needs the following changes to work with these updates:
1)  Set columns block to full-width in the Classifieds/Resources/Members section
2)  Set the group block wrapping the Community Stories Section to full-width
